# Generated by Django 4.2.2 on 2023-07-12 16:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendorregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=20)),
                ('otp', models.CharField(blank=True, max_length=8, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('Otpcreated_at', models.DateTimeField(blank=True, null=True)),
                ('Is_Approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('working_or_studying', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vendorregistration')),
            ],
        ),
        migrations.CreateModel(
            name='VendorArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Art_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('themes', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('medium', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vendorregistration')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.BigIntegerField()),
                ('Address', models.CharField(max_length=500)),
                ('panting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vendorartwork')),
            ],
        ),
    ]
